SET TIME ZONE 'Asia/Shanghai';

CREATE TABLE IF NOT EXISTS sys_dept (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_id BIGINT NOT NULL DEFAULT 0,
  ancestors VARCHAR(500) NOT NULL DEFAULT '',
  dept_name VARCHAR(64) NOT NULL,
  order_num INT NOT NULL DEFAULT 0,
  leader VARCHAR(64),
  phone VARCHAR(20),
  email VARCHAR(100),
  status SMALLINT NOT NULL DEFAULT 1,
  remark VARCHAR(500),
  created_by BIGINT,
  created_at TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by BIGINT,
  updated_at TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  is_deleted SMALLINT NOT NULL DEFAULT 0,
  CONSTRAINT uk_sys_dept_parent_name UNIQUE (parent_id, dept_name)
);
CREATE INDEX IF NOT EXISTS idx_sys_dept_parent_status ON sys_dept (parent_id, status);

CREATE TABLE IF NOT EXISTS sys_post (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_code VARCHAR(64) NOT NULL,
  post_name VARCHAR(64) NOT NULL,
  post_sort INT NOT NULL DEFAULT 0,
  status SMALLINT NOT NULL DEFAULT 1,
  remark VARCHAR(500),
  created_by BIGINT,
  created_at TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by BIGINT,
  updated_at TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  is_deleted SMALLINT NOT NULL DEFAULT 0,
  CONSTRAINT uk_sys_post_code UNIQUE (post_code),
  CONSTRAINT uk_sys_post_name UNIQUE (post_name)
);
CREATE INDEX IF NOT EXISTS idx_sys_post_status ON sys_post (status);

CREATE TABLE IF NOT EXISTS sys_role (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_name VARCHAR(64) NOT NULL,
  role_key VARCHAR(64) NOT NULL,
  role_sort INT NOT NULL DEFAULT 0,
  data_scope SMALLINT NOT NULL DEFAULT 5,
  status SMALLINT NOT NULL DEFAULT 1,
  is_system SMALLINT NOT NULL DEFAULT 0,
  remark VARCHAR(500),
  created_by BIGINT,
  created_at TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by BIGINT,
  updated_at TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  is_deleted SMALLINT NOT NULL DEFAULT 0,
  CONSTRAINT uk_sys_role_name UNIQUE (role_name),
  CONSTRAINT uk_sys_role_key UNIQUE (role_key)
);
CREATE INDEX IF NOT EXISTS idx_sys_role_status ON sys_role (status);

CREATE TABLE IF NOT EXISTS sys_menu (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_id BIGINT NOT NULL DEFAULT 0,
  menu_type SMALLINT NOT NULL,
  menu_name VARCHAR(64) NOT NULL,
  route_name VARCHAR(64),
  route_path VARCHAR(128),
  component_path VARCHAR(255),
  perms VARCHAR(100),
  icon VARCHAR(100),
  order_num INT NOT NULL DEFAULT 0,
  is_external SMALLINT NOT NULL DEFAULT 0,
  is_cache SMALLINT NOT NULL DEFAULT 0,
  is_visible SMALLINT NOT NULL DEFAULT 1,
  status SMALLINT NOT NULL DEFAULT 1,
  remark VARCHAR(500),
  created_by BIGINT,
  created_at TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by BIGINT,
  updated_at TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  is_deleted SMALLINT NOT NULL DEFAULT 0,
  CONSTRAINT uk_sys_menu_route_path UNIQUE (route_path)
);
CREATE INDEX IF NOT EXISTS idx_sys_menu_parent ON sys_menu (parent_id);
CREATE INDEX IF NOT EXISTS idx_sys_menu_type_status ON sys_menu (menu_type, status);

CREATE TABLE IF NOT EXISTS sys_user (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(64) NOT NULL,
  nickname VARCHAR(64) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  phone VARCHAR(20),
  email VARCHAR(100),
  sex SMALLINT NOT NULL DEFAULT 0,
  avatar_url VARCHAR(255),
  status SMALLINT NOT NULL DEFAULT 1,
  dept_id BIGINT,
  login_ip VARCHAR(45),
  login_at TIMESTAMP(3) WITHOUT TIME ZONE,
  pwd_updated_at TIMESTAMP(3) WITHOUT TIME ZONE,
  remark VARCHAR(500),
  created_by BIGINT,
  created_at TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by BIGINT,
  updated_at TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  is_deleted SMALLINT NOT NULL DEFAULT 0,
  CONSTRAINT uk_sys_user_username UNIQUE (username)
);
CREATE INDEX IF NOT EXISTS idx_sys_user_phone ON sys_user (phone);
CREATE INDEX IF NOT EXISTS idx_sys_user_email ON sys_user (email);
CREATE INDEX IF NOT EXISTS idx_sys_user_dept_status ON sys_user (dept_id, status);

CREATE TABLE IF NOT EXISTS sys_user_role (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  role_id BIGINT NOT NULL,
  created_by BIGINT,
  created_at TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT uk_sys_user_role UNIQUE (user_id, role_id)
);
CREATE INDEX IF NOT EXISTS idx_sys_user_role_role_id ON sys_user_role (role_id);

CREATE TABLE IF NOT EXISTS sys_role_menu (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_id BIGINT NOT NULL,
  menu_id BIGINT NOT NULL,
  created_by BIGINT,
  created_at TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT uk_sys_role_menu UNIQUE (role_id, menu_id)
);
CREATE INDEX IF NOT EXISTS idx_sys_role_menu_menu_id ON sys_role_menu (menu_id);

CREATE TABLE IF NOT EXISTS sys_user_post (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  post_id BIGINT NOT NULL,
  created_by BIGINT,
  created_at TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT uk_sys_user_post UNIQUE (user_id, post_id)
);
CREATE INDEX IF NOT EXISTS idx_sys_user_post_post_id ON sys_user_post (post_id);

CREATE TABLE IF NOT EXISTS sys_dict_type (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dict_name VARCHAR(100) NOT NULL,
  dict_type VARCHAR(100) NOT NULL,
  status SMALLINT NOT NULL DEFAULT 1,
  remark VARCHAR(500),
  created_by BIGINT,
  created_at TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by BIGINT,
  updated_at TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  is_deleted SMALLINT NOT NULL DEFAULT 0,
  CONSTRAINT uk_sys_dict_type UNIQUE (dict_type)
);
CREATE INDEX IF NOT EXISTS idx_sys_dict_type_status ON sys_dict_type (status);

CREATE TABLE IF NOT EXISTS sys_dict_data (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dict_type_id BIGINT NOT NULL,
  label VARCHAR(100) NOT NULL,
  value VARCHAR(100) NOT NULL,
  tag_type VARCHAR(30),
  tag_class VARCHAR(100),
  is_default SMALLINT NOT NULL DEFAULT 0,
  sort INT NOT NULL DEFAULT 0,
  status SMALLINT NOT NULL DEFAULT 1,
  remark VARCHAR(500),
  created_by BIGINT,
  created_at TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by BIGINT,
  updated_at TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  is_deleted SMALLINT NOT NULL DEFAULT 0,
  CONSTRAINT uk_sys_dict_data UNIQUE (dict_type_id, value)
);
CREATE INDEX IF NOT EXISTS idx_sys_dict_data_type_status ON sys_dict_data (dict_type_id, status);

CREATE TABLE IF NOT EXISTS sys_config (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  config_name VARCHAR(100) NOT NULL,
  config_key VARCHAR(100) NOT NULL,
  config_value TEXT NOT NULL,
  config_type SMALLINT NOT NULL DEFAULT 0,
  status SMALLINT NOT NULL DEFAULT 1,
  remark VARCHAR(500),
  created_by BIGINT,
  created_at TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by BIGINT,
  updated_at TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  is_deleted SMALLINT NOT NULL DEFAULT 0,
  CONSTRAINT uk_sys_config_key UNIQUE (config_key)
);
CREATE INDEX IF NOT EXISTS idx_sys_config_status ON sys_config (status);

CREATE TABLE IF NOT EXISTS sys_notice (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(200) NOT NULL,
  notice_type SMALLINT NOT NULL DEFAULT 1,
  summary VARCHAR(500),
  content TEXT NOT NULL,
  status SMALLINT NOT NULL DEFAULT 0,
  published_by BIGINT,
  published_at TIMESTAMP(3) WITHOUT TIME ZONE,
  version_no INT NOT NULL DEFAULT 1,
  remark VARCHAR(500),
  created_by BIGINT,
  created_at TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by BIGINT,
  updated_at TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  is_deleted SMALLINT NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_sys_notice_status_published_at ON sys_notice (status, published_at);

CREATE TABLE IF NOT EXISTS sys_oper_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  module VARCHAR(64) NOT NULL,
  business_type SMALLINT NOT NULL,
  method VARCHAR(100),
  request_method VARCHAR(10),
  operator_type SMALLINT NOT NULL DEFAULT 1,
  oper_name VARCHAR(64),
  dept_name VARCHAR(64),
  url VARCHAR(255),
  ip VARCHAR(45),
  location VARCHAR(128),
  request_params JSONB,
  response_data JSONB,
  status SMALLINT NOT NULL DEFAULT 1,
  error_msg TEXT,
  user_agent VARCHAR(255),
  os VARCHAR(64),
  duration_ms INT NOT NULL DEFAULT 0,
  oper_at TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
);
CREATE INDEX IF NOT EXISTS idx_sys_oper_log_oper_name ON sys_oper_log (oper_name);
CREATE INDEX IF NOT EXISTS idx_sys_oper_log_module_status ON sys_oper_log (module, status);
CREATE INDEX IF NOT EXISTS idx_sys_oper_log_oper_at ON sys_oper_log (oper_at);

CREATE TABLE IF NOT EXISTS sys_login_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(64),
  login_type SMALLINT NOT NULL DEFAULT 1,
  ip VARCHAR(45),
  location VARCHAR(128),
  browser VARCHAR(64),
  os VARCHAR(64),
  status SMALLINT NOT NULL DEFAULT 1,
  message VARCHAR(255),
  login_at TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
);
CREATE INDEX IF NOT EXISTS idx_sys_login_log_username ON sys_login_log (username);
CREATE INDEX IF NOT EXISTS idx_sys_login_log_status ON sys_login_log (status);
CREATE INDEX IF NOT EXISTS idx_sys_login_log_login_at ON sys_login_log (login_at);

CREATE TABLE IF NOT EXISTS sys_online_session (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_token_hash CHAR(64) NOT NULL,
  user_id BIGINT NOT NULL,
  username VARCHAR(64) NOT NULL,
  ip VARCHAR(45),
  location VARCHAR(128),
  browser VARCHAR(64),
  os VARCHAR(64),
  login_at TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  last_active_at TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  expires_at TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL,
  status SMALLINT NOT NULL DEFAULT 1,
  CONSTRAINT uk_sys_online_session_token UNIQUE (session_token_hash)
);
CREATE INDEX IF NOT EXISTS idx_sys_online_session_user ON sys_online_session (user_id);
CREATE INDEX IF NOT EXISTS idx_sys_online_session_status_active ON sys_online_session (status, last_active_at);

CREATE TABLE IF NOT EXISTS sys_job (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_name VARCHAR(128) NOT NULL,
  job_group VARCHAR(64) NOT NULL DEFAULT 'DEFAULT',
  invoke_target VARCHAR(255) NOT NULL,
  cron_expression VARCHAR(64) NOT NULL,
  misfire_policy SMALLINT NOT NULL DEFAULT 1,
  concurrent SMALLINT NOT NULL DEFAULT 0,
  status SMALLINT NOT NULL DEFAULT 1,
  remark VARCHAR(500),
  last_run_at TIMESTAMP(3) WITHOUT TIME ZONE,
  next_run_at TIMESTAMP(3) WITHOUT TIME ZONE,
  created_by BIGINT,
  created_at TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by BIGINT,
  updated_at TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  is_deleted SMALLINT NOT NULL DEFAULT 0,
  CONSTRAINT uk_sys_job_name_group UNIQUE (job_name, job_group)
);
CREATE INDEX IF NOT EXISTS idx_sys_job_status_next ON sys_job (status, next_run_at);

CREATE TABLE IF NOT EXISTS sys_job_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id BIGINT NOT NULL,
  job_name VARCHAR(128) NOT NULL,
  job_group VARCHAR(64) NOT NULL,
  invoke_target VARCHAR(255) NOT NULL,
  cron_expression VARCHAR(64) NOT NULL,
  status SMALLINT NOT NULL DEFAULT 1,
  message VARCHAR(500),
  exception_info TEXT,
  started_at TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL,
  finished_at TIMESTAMP(3) WITHOUT TIME ZONE,
  duration_ms INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
);
CREATE INDEX IF NOT EXISTS idx_sys_job_log_job_id ON sys_job_log (job_id);
CREATE INDEX IF NOT EXISTS idx_sys_job_log_status ON sys_job_log (status);
CREATE INDEX IF NOT EXISTS idx_sys_job_log_started_at ON sys_job_log (started_at);

CREATE TABLE IF NOT EXISTS ai_session (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  title VARCHAR(200) NOT NULL,
  status SMALLINT NOT NULL DEFAULT 1,
  last_active_at TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  created_by BIGINT,
  created_at TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by BIGINT,
  updated_at TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  is_deleted SMALLINT NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_ai_session_user_active ON ai_session (user_id, last_active_at);

CREATE TABLE IF NOT EXISTS ai_message (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id BIGINT NOT NULL,
  role SMALLINT NOT NULL,
  content TEXT NOT NULL,
  content_format SMALLINT NOT NULL DEFAULT 1,
  is_mock SMALLINT NOT NULL DEFAULT 1,
  created_at TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
);
CREATE INDEX IF NOT EXISTS idx_ai_message_session_time ON ai_message (session_id, created_at);
CREATE INDEX IF NOT EXISTS idx_ai_message_role ON ai_message (role);

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP(3);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_sys_dept_updated_at ON sys_dept;
CREATE TRIGGER trg_sys_dept_updated_at BEFORE UPDATE ON sys_dept FOR EACH ROW EXECUTE FUNCTION set_updated_at();
DROP TRIGGER IF EXISTS trg_sys_post_updated_at ON sys_post;
CREATE TRIGGER trg_sys_post_updated_at BEFORE UPDATE ON sys_post FOR EACH ROW EXECUTE FUNCTION set_updated_at();
DROP TRIGGER IF EXISTS trg_sys_role_updated_at ON sys_role;
CREATE TRIGGER trg_sys_role_updated_at BEFORE UPDATE ON sys_role FOR EACH ROW EXECUTE FUNCTION set_updated_at();
DROP TRIGGER IF EXISTS trg_sys_menu_updated_at ON sys_menu;
CREATE TRIGGER trg_sys_menu_updated_at BEFORE UPDATE ON sys_menu FOR EACH ROW EXECUTE FUNCTION set_updated_at();
DROP TRIGGER IF EXISTS trg_sys_user_updated_at ON sys_user;
CREATE TRIGGER trg_sys_user_updated_at BEFORE UPDATE ON sys_user FOR EACH ROW EXECUTE FUNCTION set_updated_at();
DROP TRIGGER IF EXISTS trg_sys_dict_type_updated_at ON sys_dict_type;
CREATE TRIGGER trg_sys_dict_type_updated_at BEFORE UPDATE ON sys_dict_type FOR EACH ROW EXECUTE FUNCTION set_updated_at();
DROP TRIGGER IF EXISTS trg_sys_dict_data_updated_at ON sys_dict_data;
CREATE TRIGGER trg_sys_dict_data_updated_at BEFORE UPDATE ON sys_dict_data FOR EACH ROW EXECUTE FUNCTION set_updated_at();
DROP TRIGGER IF EXISTS trg_sys_config_updated_at ON sys_config;
CREATE TRIGGER trg_sys_config_updated_at BEFORE UPDATE ON sys_config FOR EACH ROW EXECUTE FUNCTION set_updated_at();
DROP TRIGGER IF EXISTS trg_sys_notice_updated_at ON sys_notice;
CREATE TRIGGER trg_sys_notice_updated_at BEFORE UPDATE ON sys_notice FOR EACH ROW EXECUTE FUNCTION set_updated_at();
DROP TRIGGER IF EXISTS trg_sys_job_updated_at ON sys_job;
CREATE TRIGGER trg_sys_job_updated_at BEFORE UPDATE ON sys_job FOR EACH ROW EXECUTE FUNCTION set_updated_at();
DROP TRIGGER IF EXISTS trg_ai_session_updated_at ON ai_session;
CREATE TRIGGER trg_ai_session_updated_at BEFORE UPDATE ON ai_session FOR EACH ROW EXECUTE FUNCTION set_updated_at();
